# Generated by Django 3.1.5 on 2021-01-21 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210120_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='handle',
            field=models.TextField(default='Enter your Instagram Handle here', validators=[django.core.validators.RegexValidator(code='invalid_hashtags', message='Hashtag format invalid', regex='^ ([A-Za-z0-9._](?:(?:[A-Za-z0-9._] | (?:\\.(?!\\.))){2, 28}(?: [A-Za-z0-9._]))?)$')], verbose_name='Handles'),
        ),
    ]
