# Generated by Django 3.1.5 on 2021-01-21 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210120_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='handle',
            field=models.CharField(default='Enter your Instagram Handle here', max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_handle', message='Handle format invalid', regex='^([a-zA-Z0-9_][a-zA-Z0-9_.])*$')], verbose_name='Handles'),
        ),
    ]
