# Generated by Django 3.1.4 on 2021-01-27 09:07

import dashboard.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media/my_sell/', location='C:\\Users\\mark2\\Programming\\CeleryExample\\celery_example\\media/my_sell/'), upload_to=dashboard.models.image_directory_path, verbose_name='Image: JPEG, GIF, or PNG'),
        ),
        migrations.AlterField(
            model_name='post',
            name='small_image',
            field=models.FileField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media/my_sell/', location='C:\\Users\\mark2\\Programming\\CeleryExample\\celery_example\\media/my_sell/'), upload_to=dashboard.models.image_directory_path),
        ),
    ]
