# Generated by Django 3.1.4 on 2021-01-27 23:50

import dashboard.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210127_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('unscheduled', 'Unscheduled'), ('staged', 'Staged'), ('staged', 'Scheduled')], default='unscheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media//uploads/', location='C:\\Users\\mark2\\Programming\\CeleryExample\\celery_example\\media/uploads/'), upload_to=dashboard.models.image_directory_path, verbose_name='Image: JPEG, GIF, or PNG'),
        ),
        migrations.AlterField(
            model_name='post',
            name='small_image',
            field=models.FileField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media//uploads/', location='C:\\Users\\mark2\\Programming\\CeleryExample\\celery_example\\media/uploads/'), upload_to=dashboard.models.small_image_directory_path),
        ),
    ]
