# Generated by Django 3.1.4 on 2021-01-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210127_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('unscheduled', 'Unscheduled'), ('staged', 'Staged'), ('staged', 'Scheduled'), ('complete', 'Complete')], default='unscheduled', max_length=20),
        ),
    ]
