# Generated by Django 3.1.4 on 2021-01-30 04:22

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210128_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='handles',
            field=models.TextField(default=django.contrib.auth.models.User, validators=[django.core.validators.RegexValidator(code='invalid_hashtags', message='Handle(s) format invalid', regex='^([a-zA-Z0-9_][a-zA-Z0-9_.])\\w*$')], verbose_name='Handles'),
        ),
    ]
