# Generated by Django 3.1.4 on 2021-01-30 04:35

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210129_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='handles',
            field=models.TextField(default=django.contrib.auth.models.User, verbose_name='Handles'),
        ),
    ]
