# Generated by Django 3.1.4 on 2021-02-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210129_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='taskId',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=2200, verbose_name='Tell us about this photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='permission',
            field=models.BooleanField(default=False, verbose_name='By checking this box you are giving us permission to use this content'),
        ),
    ]
