# Generated by Django 3.1.4 on 2021-01-28 08:52

import django.core.files.storage
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210128_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media//uploads/', location='C:\\Users\\mark2\\Programming\\CeleryExample\\celery_example\\media/uploads/'), upload_to=users.models.profile_pic_directory_path),
        ),
    ]
