# Generated by Django 3.1.5 on 2021-01-20 05:35

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='small_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.jpg', editable=False, force_format=None, keep_meta=True, quality=0, size=[1920, 1080], upload_to='profile_pics'),
        ),
    ]
