# Generated by Django 3.1.5 on 2021-01-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210119_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
