# Generated by Django 3.1.5 on 2021-01-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210120_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='small_image',
            field=models.FileField(default='default.jpg', upload_to='small_images'),
        ),
    ]
