# Generated by Django 3.1.5 on 2021-01-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210120_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
