# Generated by Django 3.1.5 on 2021-01-21 05:52

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210120_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='handles',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_hashtags', message='Hashtag format invalid', regex='^ ([A-Za-z0-9._](?:(?:[A-Za-z0-9._] | (?:\\.(?!\\.))){2, 28}(?: [A-Za-z0-9._]))?)$')], verbose_name='Handles'),
        ),
    ]
