# Generated by Django 3.1.5 on 2021-01-21 05:58

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210120_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='handles',
            field=models.TextField(default=django.contrib.auth.models.User, validators=[django.core.validators.RegexValidator(code='invalid_hashtags', message='Handle(s) format invalid', regex='^[a-zA-Z0-9_][a-zA-Z0-9_.]*')], verbose_name='Handles'),
        ),
    ]
