# Generated by Django 3.1.5 on 2021-01-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210120_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='permission',
            field=models.BooleanField(default=True, verbose_name='By checking this box you give us permission you use your image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images', verbose_name='Image: JPEG, GIF, or PNG'),
        ),
    ]
