# Generated by Django 3.1.5 on 2021-01-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20210120_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='permission',
            field=models.BooleanField(default=False, verbose_name='By checking this box you give us permission you use your image'),
        ),
    ]
